### ISSUE TITLE
Send-message route should accept `northstarId` instead of mobile.

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit-conversations#154]
## Spec
- The route `send-message` will expect `northstarId` instead of `mobile`.
- All other params stay the same: `template`, `slackId`, and `campaignId `.

The route will have to make a lookup to NS to get the mobile number of the user.

## Done
- Request
```
curl -X "POST" "https://gambit-conversations-staging.herokuapp.com/api/v1/send-message" \
-H "Content-Type: application/json; charset=utf-8" \
-u "puppet:secret" \
-d $'{"northstarId":"vjs57cre67scvsecg", "campaignId":"48","template":"externalSignupMenu"}''
```
- Response should be:
```
{
  "data": {
    "messages": [
      {
        "_id": "59d502649d2d750004776f03",
        "updatedAt": "2017-10-04T15:46:44.067Z",
        "createdAt": "2017-10-04T15:46:44.067Z",
        "text": "Hey - this is Freddie from DoSomething. Thanks for joining Pride Over Prejudice!\n\nA new White House executive order denies all new refugees entry to the US for 120 days and places a 90-day travel ban on six Muslim-majority nations.\n\nThe solution is simple: Post a selfie to stand in solidarity with refugees and immigrants.\n\nMake sure to take a photo of what you did! When you have Shared some Pictures, text START to share your photo.",
        "direction": "outbound-api-send",
        "template": "externalSignupMenu",
        "conversationId": "59b72e6c3ceb08001237978f",
        "campaignId": 48,
        "topic": "campaign",
        "broadcastId": null,
        "__v": 0,
        "metadata": {
          "requestId": "d7589fb2-11b7-445f-847a-5ee521a9ecac"
        },
        "attachments": []
      }
    ]
  }
}
```

Based on O'Dev Jam (10/3/17)  [Link 1](https://dosomething.slack.com/archives/C2C8NLNAY/p1507054504000446?thread_ts=1507050443.000351&cid=C2C8NLNAY) [Link 2](https://dosomething.slack.com/archives/C2C8NLNAY/p1507053595000180?thread_ts=1507050443.000351&cid=C2C8NLNAY).

cc @sergii-tkachenko @aaronschachter @DFurnes

**Comment by rapala61** [comment]
@aaronschachter should we keep the route backwards compatible to also accept `mobile`? I think it would be a good idea.

**Comment by aaronschachter** [comment]
Why keep it? Nothing is currently posting here except Front (which just posts a Front message)

**Comment by rapala61** [comment]
I think is reasonable to assume we might need this flexibility in the future.

**Comment by sergii-tkachenko** [comment]
I'd argue that we need to use `id` instead of `northstarId`. The logic is on different platforms we'd use this field to identify the user. Pseudocode:

```
getUser(id, platform) {
  if platform == 'Northstar' then return loadNorthsarUser(id);
  if platform == 'Slack' then return loadSlackNorthsar(id)
}
``

**Comment by sergii-tkachenko** [comment]
Also, I just noticed that you didn't use `platform` variable. I think it'll make the request more explicit.

**Comment by rapala61** [comment]
@sergii-tkachenko I agree, but the limitation we have is that the `platform` param is not consistently used this way. Basically, `platform` is deduced from the payload of the request, not explicitly from getting the `platform` param.

**Comment by sergii-tkachenko** [comment]
I assume it's deduced in Front integration?

**Comment by rapala61** [comment]
In the case of Slack for example, how do we determine that the platform is `slack`? We sniff for the `req.body.slackId` param.

**Comment by rapala61** [comment]
@sergii-tkachenko in the case of Front, is by sniffing for the header `req.headers['x-front-signature']`.

**Comment by rapala61** [comment]
@sergii-tkachenko @aaronschachter I guess we can refactor this whole route in the near future, for now, I think is best for me to stay within scope and implement the functionality to accept `northstarId`.

**Comment by sergii-tkachenko** [comment]
I recommend not to do that. Sending different payload types to the same endpoint is an easy way to make mistakes. You're combining external payloads that we don't control with internal integrations that expected to be in a certain format.

For example, how do you expect Slack or Front to send `campaignId` to `template`?

**Comment by sergii-tkachenko** [comment]
@rapala61 Beat me to it, my last comment was to https://github.com/DoSomething/gambit-conversations/issues/154#issuecomment-334253475 and https://github.com/DoSomething/gambit-conversations/issues/154#issuecomment-334253475.

**Comment by sergii-tkachenko** [comment]
Ok, I agree. Let's go with the path of least resistance for now, but plan the refactoring as a post-release improvement.

**Comment by rapala61** [comment]
@sergii-tkachenko I like your suggestions, they are great! It's just that to implement I would have to refactor work both @aaronschachter and I have implemented. Refactoring a few things is in our minds for V✌️.
