### ISSUE TITLE
Temporary feature request: filter out members with no phone number on /send-message

### ISSUE THREAD

**Issue by sergii-tkachenko** [DoSomething/gambit-conversations#162]
### Existing behavior
When Blink posts a `signup_post` that belongs to a user with no phone number to Gambit's `/send-message`, the request fails with:
```
response_status=500 response_status_text="Internal Server Error" {"message":"The string supplied did not seem to be a phone number"}
```
As a side-effect, Blink will enter this request into undesirable retry loop.

### Temporary solution
Either filter out (ignore) this kind of messages or suppress undesired retries in Blink by setting `x-blink-retry-suppress: true` header on the response.

### Optimal solution
When Blink has a feature that would allow extending known messages with data from other resources (in this case extending Rogue's `signup_post` with Northstar's profile user info), it will be able to filter out signup posts of users with no phone number on their profile and not send these requests to  Gambit's `/send-message`.
Related feature request in Blink: **pending**.

### Related tickets
This came up during https://github.com/DoSomething/blink/pull/147

**Comment by aaronschachter** [comment]
I remember the Quicksilver request to Gambit Campaigns `POST /signups` filtering out any Signups with source equal to `sms-mobilecommons`.  [The `POST /signups` has an additional sanity check to return a 208 if we get one](https://github.com/DoSomething/gambit/blob/4.8.0/app/routes/signups.js#L41).

Do we also need to filter by the Signup source, to avoid sending `externalSignupMenu` messages for Signups that are created via Gambit?

**Comment by sergii-tkachenko** [comment]
@aaronschachter Quicksilver is using Phoenix Ashes as a data source of signups. Because Ashes use to be a source of user data for some time, it still has some user profile data we can pass along with signups.

Currently, blink just doesn't have access to user profile data in signups. That's why I'm asking for this temporary feature to perform checks in Gambit Campaign.

**Comment by sergii-tkachenko** [comment]
> Do we also need to filter by the Signup source, to avoid sending externalSignupMenu messages for Signups that are created via Gambit?

I don't understand this part of the question. Blink does not send signup source field to `/send-message`. It'll be easy to change it if think it's going to be useful.

**Comment by aaronschachter** [comment]
Quicksilver + Gambit Campaigns filters `POST /signups` requests to avoid sending two messages for a Signup keyword:
1 - `gambitSignupMenu` - sent for a Campaign keyword that creates a Signup
2 - `externalSignupMenu` - sent by Quicksilver when a Signup is created

<img width="1194" alt="screen shot 2017-10-13 at 2 32 30 pm" src="https://user-images.githubusercontent.com/1236811/31567301-af6966fa-b023-11e7-92ef-a1f3c14338f2.png">
