### ISSUE TITLE
Send message TypeError: Cannot read property 'externalSignupMenu' of undefined

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-conversations#189]
Requests from Blink are triggering this on staging and my hunch is that we're receiving requests for Campaigns that aren't running on Gambit.

In a Gambit Campaigns `POST /signups` request (which will be replaced by posting to the Conversations `POST /send-message), we return a 422 if the target Campaign is [closed](https://github.com/DoSomething/gambit/blob/4.9.0/app/routes/signups.js#L82) or doesn't have any [published keywords](https://github.com/DoSomething/gambit/blob/4.9.0/app/routes/signups.js#L105).

**Comment by aaronschachter** [comment]
From @sergii-tkachenko via Slack:

> Yup. Blink is sending all to Gambit now. @rapala61 and I discussed this eariler and decided to filter them out in gambit.

`POST /send-message` is currently filtering for closed Campaigns, but not for Campaigns that aren't available on Gambit. What should the response be for those requests?

**Comment by rapala61** [comment]
Gambit Campaigns `POST /signups` is responding with 422, but it's not suppressing retries. Just to confirm, are 422 being retried @sergii-tkachenko ? If not, I will have to also add suppress retry headers with the 422 response in `/send-message`.

**Comment by aaronschachter** [comment]
Gambit Campaigns `POST /signups` also isn't expecting the request, since Quicksilver is filtering for Gambit Campaigns. We'll constantly be getting 422 errors... what do yous think about sending a [204 No Content?](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml)

**Comment by rapala61** [comment]
This part trips me a little about the 2xx in this context: "The action was successfully received, understood, and **accepted**". Nobody would understand this situation if they are not as heads down as we are in the TGM transition.

We would be getting constant 422's indeed, but they are valid 4xx: "The request contains bad syntax or **cannot be fulfilled**".

If we all agree on this tradeoff, I'm ok, I understand the reason, I just feel a little yucky about it 😅.

**Comment by aaronschachter** [comment]
I feel that, just wanted to throw the idea out there. The stress level of constant 422's would quickly go away if we set New Relic to ignore them -- but that feels a little dicey when it's crucial to know about 422's thrown from Northstar or Gambit Campaigns. It's where at least logging the Campaign Id in New Relic as a custom parameter (like we do in https://github.com/DoSomething/gambit/issues/834) would be helpful if New Relic is our go-to for error monitoring (which I think it is, vs Logstash)

**Comment by rapala61** [comment]
Given the tradeoffs, I'm fine with implementing your 204 idea. I'll slap a `//TODO` so we can add some preprocessing to Blink in the future, since this is something that I would preferred it to be handled before it reaches us.

**Comment by rapala61** [comment]
Based on the conversation in [Campaigns#990](https://github.com/DoSomething/gambit/issues/990). This issue is due to a bug in the way we handle errors in the 'gambit-campaigns' lib.

>Bug#2 - Convo#189: There is a [bug](https://github.com/DoSomething/gambit-conversations/blob/master/lib/gambit-campaigns.js#L26) when catching errors in the `executeGet` (and other methods) of the `gambit-campaigns` lib that returns the error response as a false positive response. This makes the parent promise believe it is receiving a valid campaign when its actually receiving an error object. My hunch is that Convo#189 is directly related to this bug.
