### ISSUE TITLE
Update broadcast-settings route to comply with latest Broadcast process

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit-conversations#215]
# Story
As an O'dev staff, I want to be able to get the correct settings for a Customer.io broadcast, so that the broadcast goes through Blink first, instead of directly to Twilio from Customer.io webhooks.

# Current Behavior
`/broadcast-settings` route is returning outdated data that assumes broadcasts are still being sent directly to Twilio from Customer.io

# Spec
- [x] `webhook.url` value must point to Blink's `/api/v1/webhooks/customerio-sms-broadcast` endpoint instead of Twilio's `/2010-04-01/Accounts/ACXX/Messages.json" endpoint.
- [x] `webhook.headers.Content-Type` value should be `application/json` instead of `application/x-www-form-urlencoded`.
- [x] `webhook.body` value must be in JSON format from URI encoded.
- [x] Update Docs.

# Pending Spec items
- [x] Should we keep the `StatusCallback` property in the `webhook.body` object? If so, what should be the value? Answered here: https://github.com/DoSomething/gambit-conversations/issues/215#issuecomment-342928770

**Comment by rapala61** [comment]
If the Cusomer.io Webhook URL uses this patter: `blink.dosomething.org/api/v1/webhooks/customerio-sms-broadcast?broadcastId=<BROADCAST-ID>` would the `broadcastId` get picked up by Blink? @sergii-tkachenko

**Comment by sergii-tkachenko** [comment]
It would, but it'd make more sense to just put it in JSON payload. There's no need to use `GET` query now.

**Comment by sergii-tkachenko** [comment]
>  Should we keep the StatusCallback property in the webhook.body object? If so, what should be the value?
Nope. No need to keep this any longer.

**Comment by rapala61** [comment]
> It would, but it'd make more sense to just put it in JSON payload. There's no need to use GET query now.

Ok. So sending `broadcastId, To, and Body` properties in the body would be enough right?

**Comment by sergii-tkachenko** [comment]
Yep. Let's improve naming for `To` and `Body` though. How about `mobile` and `body`? Or `phone` will be better?

**Comment by sergii-tkachenko** [comment]
Yep. Let's improve naming for `To` and `Body` though. How about `mobile` and `body`? Or `phone` will be better?

**Comment by sergii-tkachenko** [comment]
Yep. Let's improve naming for `To` and `Body` though. How about `mobile` and `body`? Or `phone` will be better?

**Comment by rapala61** [comment]
@sergii-tkachenko but wouldn't these name changes add work on the Blink side? what about if I just keep them the same for now, and next week we make improvements on both sides? Also, `mobile` is more consistent with how we refer to user phone numbers in Convo so I would prefer that.

**Comment by sergii-tkachenko** [comment]
Sure!

If these are cosmetic changes only, it makes sense. In this case, we should keep `StatusCallback` and doen't send `broadcastId` as a separate field. Actual URL in `StatusCallback` doesn't matter, the only requirement is to end it with `broadcastId=broadcast_id_here`.

**Comment by rapala61** [comment]
Hey @sergii-tkachenko, I found something that is a blocker to solve this issue.

- It seems that Blink is relying on the body to be url-encoded, which makes sense because that's what we were sending, but it doesn't like the fact is receiving `aplication/json` content. Could it be because of the `+` sign logic you implemented on this field. 

#### The webhook
<img width="1120" alt="screen shot 2017-11-08 at 6 37 04 pm" src="https://user-images.githubusercontent.com/863301/32580572-e688a9d0-c4b3-11e7-9066-d06728346b63.png">


#### This is the error I see when executing the above webhook
<img width="576" alt="screen shot 2017-11-08 at 6 27 07 pm" src="https://user-images.githubusercontent.com/863301/32580371-fc703bec-c4b2-11e7-9f92-73b6acd7eb60.png">

#### This is what I get locally if I point the webhook to my ngrok tunnel.
>Redacted for security.
```
{
  "To": "+15555555555",
  "Body": "Do you like tacos puppet? Want to sign up for mirror messages?  puppet is your name right?",
  "StatusCallback": "http://<secret>:<secret>@blink-staging.dosomething.org/api/v1/webhooks/customerio-sms-broadcast?broadcastId=7zU0Mb1k9GkWWI40o06Mic"
}
```

**Comment by sergii-tkachenko** [comment]
Right. The reason for that actually lies in a bug in the previous implementation. It used to generate request body like this:
`To={{customer.phone}}&Body=...`

Note that E.164 all start with `+` sign, which, in fact, is treated as a whitespace by `application/x-www-form-urlencoded` standard. That's why we customer.io was sending ` 15555555555` instead of `+15555555555` to Twilio.

That's why I had to adjust for this behavior in Blink too. Phone numbers are expected with whitespace instead of `+` in the beginning now.

**Comment by sergii-tkachenko** [comment]
Since it requires a patch in Blink, I'd recommend not to implement this cosmetic change for now, unless there's a necessity for special characters.

**Comment by rapala61** [comment]
Ya. That was a bug due to the Twilio's technical limitation that it only supports `application/x-www-form-urlencoded`, but Customer.io expects liquid tags to interpolate values that are not `application/x-www-form-urlencoded` friendly. 

>That's why I had to adjust for this behavior in Blink too. Phone numbers are expected with whitespace instead of + in the beginning now.

How challenging is to update this implementation to accept both numbers with space or with a `+` sign? I think t's going to be really important for freddy and kika to have the `/broadcast-settings` route return valid settings for the current Blink workflow. Although, if we can't make this change in Blink and Convo today, they could manually paste the Blink's `customerio-sms-broadcast` URL. Not ideal, but also solves this problem until you can update Blink.

**Comment by sergii-tkachenko** [comment]
Not very challenging, just need to test it properly.
Yes, the plan is to use old settings and just update it with Blink's endpoint. I've showed Freddie how to do it.
