### ISSUE TITLE
Refactor cache implementation for Campaigns.

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit-conversations#217]
# Summary
The current implementation of `cacheman` in the `lib/phoenix` module should be refactored since the single campaign endpoint is being cached at the Gambit Campaigns API level with Redis.

# Spec
TBD.

**Comment by aaronschachter** [comment]
We're planning on migrating all Contentful queries into gambit-campaigns, does it make sense to close this by removing our cache helper entirely and always fetching from gambit-campaigns?
