### ISSUE TITLE
Outbound message loading bug

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit-conversations#219]
# Bug
On retry, Convo attempts to load last inbound message and last outbound so to not create dupes of these when a request has failed and it's being retried. This mechanism assumes that an outbound message was created as part of the first attempt, but in some cases, the request fails before an outbound message is created and added as the `lastOutboundMessage` property of this user's Conversation.

#### Example: 
User with number `+15555555555` texted "Dream"
```
// Blink log
{"ToCountry":"US","ToState":"","SmsMessageSid":"SMXX","NumMedia":"0","ToCity":"","FromZip":"37216","SmsSid":"SMXX","FromState":"TN","SmsStatus":"received","FromCity":"NASHVILLE","Body":"Dream","FromCountry":"US","To":"SHORTCODE","MessagingServiceSid":"MGXX","ToZip":"","NumSegments":"1","MessageSid":"SMXX","AccountSid":"ACXX","From":"+15555555555","ApiVersion":"2010-04-01"}
```

The user had no messages in it's message history. The first message failed, because of an [H12](https://devcenter.heroku.com/articles/error-codes#h12-request-timeout). It created an inbound message but no outbound message. Notice the `metadata.retryCount`.

```
// Conversation, missing lastOutboundMessage
{
    "_id" : ObjectId("5a05aa08235b7900044d2058"),
    "updatedAt" : ISODate("2017-11-10T13:30:49.479Z"),
    "createdAt" : ISODate("2017-11-10T13:30:48.170Z"),
    "platformUserId" : "+15555555555",
    "platform" : "sms",
    "paused" : false,
    "topic" : "campaign",
    "__v" : 0,
    "campaignId" : 7927,
    "signupStatus" : "doing"
}
// Inbound message, no outbound message created
{
    "_id" : ObjectId("5a05aa08235b7900044d2059"),
    "updatedAt" : ISODate("2017-11-10T13:50:45.391Z"),
    "createdAt" : ISODate("2017-11-10T13:30:48.700Z"),
    "text" : "Dream ",
    "direction" : "inbound",
    "template" : null,
    "conversationId" : ObjectId("5a05aa08235b7900044d2058"),
    "topic" : "random",
    "platformMessageId" : "SMXX",
    "metadata" : {
        "requestId" : "17771be8-XXXX-4baf-XXXX-56a3e3de184d",
        "retryCount" : 527
    },
    "attachments" : [],
    "__v" : 0
}
```

Convo Heroku logs display the following error on each retry:
```
2017-11-10T13:48:40.321978+00:00 app[web.10]: code=500 response#message="Cannot read property 'text' of undefined" level=error message=sendResponseWithStatusCode
```
After some troubleshooting, I found the cause here: 
https://github.com/DoSomething/gambit-conversations/blob/master/app/models/Conversation.js#L291. Since`lastOutboundMessage` is undefined, attempting to get it's `text` property generates a 500 error.

https://github.com/DoSomething/gambit-conversations/blob/master/lib/helpers.js#L161. Because this request is being retried, this behavior will continue to occur, unless it's manually republished from Blink with a `retryCount` of 0. Giving it a chance to reprocess both the inbound and outbound. The problem with this workaround is that we have to manually delete the first instance of the inbound message that got stuck with a retryCount.

**Comment by rapala61** [comment]
cc @justkika can we get this one in for the next sprint?

**Comment by aaronschachter** [comment]
[Docs](https://docs.google.com/document/d/1uQ1sh8Izep6vMmd7myryub_a-zemFIRNGHWI0uCUBQ0/edit#) for steps to manually fix when this occurrs.
