### ISSUE TITLE
Our DB is getting closer to the size limit. 125GB/110GB.

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit-conversations#338]
We have to do some index maintenance in this DB. There are a ton of indexes that are actually consuming most of the allowed size. We have to analyze which indexes are used most frequently, keep those and remove the rarely used indexes.

**Comment by rapala61** [comment]
Currently at `127GB of 127GB Storage` after the re-permissioning broadcast. Compose will auto scale in 1 GB intervals until the earth stops spinning 🤑.

**Comment by ngjo** [comment]
Pivotal: https://www.pivotaltracker.com/story/show/158796807

**Comment by aaronschachter** [comment]
Cross-posting link to [Quasar integration discussion](https://github.com/orgs/DoSomething/teams/storm/discussions/2), as ideally it should eliminate the need for a few of the indices we've used for broadcast aggregation/investigation.

**Comment by ngjo** [comment]
@rapala61 quick q -- of the indices removed, did you remove yet any of the ones that @aaronschachter flagged here that we might not need post-quasar integration? just want to make a card to double back to this post-quasar integration if we need to

**Comment by rapala61** [comment]
I think we should make a bullet point somewhere to reintroduce this topic once we have integrated with quasar. @aaronschachter can probably add more about what he thinks is the best way to integrate w/ Quasar but I don't think we have a set of indexes already defined that we could remove as a product of integrating (as far as I know).
