### ISSUE TITLE
Sending a subscriptionStatusActive template to all new users

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-conversations#365]
_EPIC OVERVIEW_
-------------------
#### User Story

As a messaging team member, I want new users on web or SMS to receive a CTIA compliant message confirming the user's SMS subscription.

#### Web registrations
Blink will post to a new `messages?origin=subscriptionStatusActive` endpoint to deliver a `subscriptionStatusActive` message to the user. We may need to create a new conversation for this user - the default topic of `'random'` should be sufficient, as the user will eventually be prompted to text MENU to begin a campaign if they send a message that doesn't match any triggers.

* https://www.pivotaltracker.com/story/show/158460231
* https://github.com/DoSomething/blink/pull/211

#### SMS registrations
We've been talking sending two messages via the `messages/member` middleware 1 -- the `subscriptionStatusActive` and 2 -- whatever the reply the trigger should deliver. This makes our retry logic a bit more complicated. We only want to send the first message when we first create the user -- but it's possible a request could fail after creating that first `message` document. @rapala61 and I chatted about this on Friday 7/6 and there are a few ways this can go, I'm going to talk through is a bit more in a comment below.

* https://www.pivotaltracker.com/n/projects/2092729/stories/158416299

#### Why This Matters

https://support.twilio.com/hc/en-us/articles/223134707-Industry-Standards-for-opt-ins-for-US-Short-Codes

**Comment by aaronschachter** [comment]
Sending the welcome message for a new user created via `sms` in addition to the Gambit reply is tricky when it comes to retries. If a `POST messages?origin=twilio` request that should create a new user is retried, a NS user may exist this time around -- and we may already have created an outbound `subscriptionStatusActive` message to send the user but never delivered it because the request failed.  We'd need to save this `requestId` when successfully creating a new NS user, and then check whether we have the `subscriptionStatusActive` created with the same `metadata.requestId` set when retrying a request (because we don't want to create a new outbound `subscriptionStatusActive` message for each retry).

Implementation ideas:

1. Always create/send the welcome message via `POST /messages?origin=subscriptionStatusActive`, and leave `POST /messages?origin=twilio` as is. The gotchas here are:

    * Cannot ensure the welcome message will arrive before the reply

    * A new user who texts JOIN will receive 2 `subscriptionStatusActive` messages, the second from the JOIN trigger. This is likely rare to happen as we typically advertise a campaign or influencer keyword instead of JOIN

2. Keep as is, sending a single reply (and filtering `POST /messages?origin=subscriptionStatusActive` requests by `user.source_detail` to only send for non sms registrations) per [Twilio docs that state a "double opt-in process is advised, but not required" for handset opt-ins](https://support.twilio.com/hc/en-us/articles/223134707-Industry-Standards-for-opt-ins-for-US-Short-Codes). Because they're not required, it seems the out-of-order gotcha in #1 shouldn't be a deal breaker

3. Build out the  `messages/member` middleware to support retries for multiple outbound messages, per the details in the beginning of this comment. There's always been a wishlist feature to support multiple outbound messages in a Gambit reply anyway, as the signup confirmation messages require a few line breaks to keep the content readable. If we go this route, @rapala61 and I were chatting about potentially refactoring sending replies via Twilio by having Blink send instead of Gambit Conversations, as Blink could iterate through the `messages.outbound` array returned in a successful `POST messages?origin=twilio` response.

cc @ngjo

**Comment by aaronschachter** [comment]
If we go with #1 (which is feeling a bit like the winner to me at the moment), we'll need to edit the web signup confirmation templates in Contentful to no longer include the compliance messaging.

**Comment by aaronschachter** [comment]
Forward thinking - there's a feature request for an influencer topic, where we'll want to override the `subscriptionStatusActive` template text with something custom, e.g. "Hi it's DoSomething and Shawn! You're signed up for X with 8 msg/mo etc" and additionally send the first message in the topic.

This is where approach #3 feels like the cleanest way to implement, although it's for sure a doozy.

For approach #1 -- this override could be handled by the `lib/middleware/messages/subscriptionStatusActive` if we finally begin to save the inbound message `match` as the user's `source_detail`(#170 ). The `subscriptionStatusActive` middleware would check a user's `source_detail` to see if it's a trigger for a topic, and could return an  `subscriptionStatusActive` template value to use for the user registration message text.

**Comment by ngjo** [comment]
At sprint plan today, we discussed this and we're:

- Ok with the messages possibly sending out of order
- Ok with current functionality to stay the same

I'll be making icebox cards to revisit the current functionality around how we create active accounts and digging more into multiple messages over Gambit

**Comment by aaronschachter** [comment]
Was chatting about this with @mirie in 1:1 today and she flagged we may want to tweak our `subscriptionStatusActive` template knowing it may arrive out of order, e.g a 2nd message that says "These are DoSomething Alerts 8 msg/month" will read better out of order than "Hi it's Freddie!"
