### ISSUE TITLE
Finalize schema + endpoints

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-conversations#39]
Opening to discuss the structure of our current models and endpoints, with some notes on some of the naming decisions. Questions, comments, concerns?  

## Conversation

| Name | Type | Notes |
| --| -- |-- |
| platform* | String | `sms`, `slack`, `facebook`
| platformUserId* | String | The identifier of the sender per their platform. e.g. `'+2125552312'`, `'U03T8S7JC'`
| paused | Boolean | If true, the bot will not respond. This conversation requires an agent.
| topic | String | [The current Rivescript topic](https://www.rivescript.com/docs/tutorial#topics), used to determine replies
| campaignId | Number | The current DS Campaign the conversation is about.
| signupStatus| String | Used to determine how to reply (`doing`, `prompt`,`declined`) 
| lastOutboundTemplate | String | Used to determine whether to direct conversation back to Campaign topic | 
| slackChannel | String | Needed to DM a Slack User
| lastBroadcastId | String | The current broadcast prompting Signup for the `campaignId`
| createdAt | Date | date the conversation was created

*Refs [chatbot schema of the Hilary Campaign](https://docs.google.com/document/d/1CMlG1v9AAln9SvI4Ysqo8NOd4L4ObDy3SY8pNh9iXhI/edit)

## Message
| Name | Type | Notes |
| --| -- |-- |
|  conversationId | ObjectId | refs our `Conversation` model
| platformMessageId | String | The Message's ID internal to its service (Twilio `MessageSid`) #52
| direction* |  String  | `'inbound'`, `'outbound-reply'`, `'outbound-api-send'`, `'outbound-api-import'`
| campaignId | Number | 
| broadcastId | String | Broadcast id this message is associated with (if any)
| topic|  String| 
| template | String | e.g. `signupDeclinedMessage, askQuantityMessage`
| text | String | 
| attachments | Array | #31 
| agentId | String | The Member Support Agent who sent the message (#32) 
| createdAt | Date | date the message was created

*Refs [Twilio Messages API](https://www.twilio.com/docs/api/rest/message)

## Endpoints

**POST** `/receive-message` - Creates an Inbound Message for Conversation of the sender. 
  * If Conversation is not paused, creates an Outbound Reply Message and sends it to the member
  * If Conversation is paused -- posts the inbound message to our Gambit Support custom channel in Front.

**POST** `/send-message` - Sends the payload to create a Conversation Message and send it to the member
   * Our Gambit Support custom channel posts outgoing messages from Front to this endpoint to post the Front message text to the Conversation medium
   * Blink will post to this endpoint to deliver External Signup Messages for a given Campaign

**POST** `/import-message`- (#34) Creates a copy of the Message to store in the Conversation, when the message was sent from an 3rd party service (e.g. Customer.io)

**Comment by aaronschachter** [comment]
Also just remembered we're missing Broadcast ID -- we need it to store the current Broadcast ID on the Conversation as well, to include in the payload to the Gambit Campaigns API that creates the Signup. Editing the issue to add it in.

**Comment by rapala61** [comment]
@aaronschachter I'm going to add the `broadcastId`property to the Conversation model here: #34

**Comment by aaronschachter** [comment]
https://github.com/DoSomething/gambit-conversations/issues/56

**Comment by aaronschachter** [comment]
This came up today, I think it could make sense to rename `Conversation.broadcastId` as  `Conversation.lastBroadcastId`, similar to `Conversation.lastOutboundTemplate`

**Comment by DFurnes** [comment]
From our call yesterday: I like the idea of renaming `userId` to `mediumId` for clarity, and leaving open the possibility of storing the user's Northstar ID as `userId` once they've signed up or reported back for a campaign.

I also feel like the `POST /receive-message` and `POST /send-message` are a little confusing at first glance. If I'm understanding them correctly, could it make sense to rename them to `POST /response` for inbound messages from users and `POST /message` for outbound messages? It also feels a little more RESTful without the verbs in the URL, which is kinda nice. 😌

Could you also share me on the Hillary schema doc? I'm not allowed to view it.

**Comment by aaronschachter** [comment]
Thanks @DFurnes ! 

* Fixed the link on the Hilary Google docs in the description

* What do we think of `mediumUserId` (vs `mediumId`) ? This could match nicely with proposed `mediumMessageId` in #52 

* The understanding on receive-message and send-message is correct. There's a third `/import-message`, where a 3rd party is sending a message to the User (e.g. Mobile Commons or customer.io broadcast), but we want to store a copy of the message for a full Conversation profile. @rapala61 and I talked about a general POST message endpoint for both.. but it does make actually using the API a bit trickier.  POST `/reply` could potentially be a little more clear than POST `/response` -- but we'd never GET /reply -- only GET message (inbound and outbound messages are all available in a GET /messages endpoint)

**Comment by rapala61** [comment]
@aaronschachter @DFurnes what is the standard across projects when it comes to date? I'm used to the usual createdAt/updatedAt columns to keep track of times.

**Comment by DFurnes** [comment]
> @aaronschachter @DFurnes what is the standard across projects when it comes to date? I'm used to the usual createdAt/updatedAt columns to keep track of times.

Oh, good catch! We use standard `created_at` and `updated_at` columns most places, storing them however the database wants and returning [ISO-8601 date strings](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations) in API responses.

**Comment by DFurnes** [comment]
> * Fixed the link on the Hilary Google docs in the description

Thanks thanks! 🙇 

> * What do we think of `mediumUserId` (vs `mediumId`) ? This could match nicely with proposed `mediumMessageId` in #52 

Yeah, I'm into that. More clarity always seems better. 👍

**Comment by rapala61** [comment]
@aaronschachter it's ok if I udate the schema table in this issue to reflect adding `createdAt` and `updatedAt` columns? We would leave `date` for backwards compatibility.

**Comment by aaronschachter** [comment]
Sure. I don't think we need to worry about backwards compatibility. I've been considering whether we should open a google doc to finalize and comment - but I'm down to make the updates in issue description.  I've just updated `userId` to `mediumUserId` per https://github.com/DoSomething/gambit-conversations/issues/39#issuecomment-322845860

FYI  - Mongoose has a handy [timestamps](http://mongoosejs.com/docs/guide.html#timestamps) feature.

**Comment by rapala61** [comment]
@aaronschachter yeah, its pretty easy to just add an option to generate them on the fly. 😄

**Comment by rapala61** [comment]
Added `createdAt` for both schemas.
Added `broadcastId` to the Message schema.
Renamed `broadcastId` to `lastBroadcastId` in the Conversation schema.

**Comment by aaronschachter** [comment]
I've added `mediumMessageId` to the `Messages`, to store the internal Twilio Message Sid, Facebook, Slack message ID etc for each message we receive, but for also each outbound message we post. (Refs #73)

Two questions I'd love to get a 👍 or 👎 on:

1. Initially I created the `medium` property as `platform`, which is why you'll see `req.platform` all over. Thinking through our `sms` medium and `mediumMessageId` -- our medium is SMS but our Message Id could belong to Mobile Commons, or Twilio... which makes me reconsider using `platform` instead of `medium`... so it'd be `Conversation.platform`, `platformUserId`, `platformMessageId` vs `medium`. Would love to know if you feel one way or the other

2. I'm beginning to warm up to the idea of single POST `/messages` endpoint to replace `/send-message`, `/import-message`, and `/receive-message`, using a query parameter to specify the message direction, if it helps to clarify API usage.

* **POST** `/messages?direction=inbound` (when a User has sent a message and we want to reply, or forward to Support)

* **POST** `/messages?direction=outbound-send` (when we're sending a message on behalf of another service, e.g. Support Agent responds, Confirmation of Web Signup, Relative Reminder message)

* **POST** `/messages?direction=outbound-import` (when the message has already been sent to a User from another service, and we're importing the Message and updating their Conversation state accordingly)

Yay, nay?

**Comment by rapala61** [comment]
1. 👍 
2. After coding the `import-message` and working with `receive-message`, I've grown fond of the idea of keeping them separate. Mainly because of 🐛  isolation. We could potentially make updates individually to one of the endpoints without affecting the others. Although I do see how a single endpoint could make anyone consuming the API happier.

**Comment by aaronschachter** [comment]
Updated the properties to `platform`, `platformUserId`, and `platformMessageId`.

Two more questions:
* `Message.conversation` -- Named this as `Message.conversation` vs `Message.conversationId`, because I was thinking it'd play nicer with [Express Restify Mongoose](https://github.com/florianholzapfel/express-restify-mongoose) -- if we wanted the Conversation object embedded in a Message, it'd make more sense to appear as `conversation: { }` then `conversationId: { }`. Right now we're not loading a `conversation` but just returning the Conversation ID -- http://gambit-conversations-staging.herokuapp.com/api/v1/messages

What's best? This brings up the 2nd question:

* `Message.platformUserId` -- was keeping this here because it seemed convenient for viewing all [Latest Reply Messages](https://gambit-admin.herokuapp.com/), or a view where we'd want to filter messages by Campaign. If the `Message.conversation` is a loaded object, we don't need the `platformUserId` here...

**Comment by aaronschachter** [comment]
Going with `Message.conversationId`
