### ISSUE TITLE
Potential Rivescript brain fetch/sorting bug on restart.

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit-conversations#391]
_BUG_
-------------------
#### Current Behavior
- It seems like on restart, the staging environment did not fetch and sort the rivescript until it receive a request.

#### Desired Behavior
- Should fetch and sort rivescript on restart.

#### Steps to Replicate
- I restarted G-Conversations staging and did not see the usual logs about the brain
- About 7 mins later I sent `hi` through slack and got a `500` error: `Still sorting bot replies, please retry your message.` x 2.
- I got the correct `hi` response after my 3rd time.
- Attached is a screenshot of the staging Heroku logs.

#### Relevant Screenshots + Links

<img width="1438" alt="screen shot 2018-08-28 at 1 00 39 pm" src="https://user-images.githubusercontent.com/863301/44741577-202d8980-aac3-11e8-9d1e-3ae613b96d8e.png">

**Comment by aaronschachter** [comment]
@rapala61 this is expected behavior per #390, which i deployed to staging last night to test.

**Comment by rapala61** [comment]
Ah! ok, I'll review that PR to understand the behavior 👍.
