### ISSUE TITLE
Store external Message ID's in our Messages

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-conversations#52]
We'll want a property named something like `mediumMessageId` that corresponds to the Twilio, Messenger, or Slack ID for both an inbound message, and the outbound messages we create and post to the respective platform API.

## Updated scope

Property name will be `platformMessageId`.

Refs #39

**Comment by rapala61** [comment]
@aaronschachter 

I want to confirm the different `platformMessageId`s, but I am having a hard time with the Facebook one:

Twilio | Slack | Facebook
--- | ---- | ---- 
`MessageSid` | `slackId` | ?

**Comment by rapala61** [comment]
ping

**Comment by aaronschachter** [comment]
Since we're not launching on Messenger yet, I don't think we need to support it. Slack and Facebook messages are both forwarded to the gambit-adapters, which posts to gambit-conversations.

The Gambit Adapters Facebook route follows the Messnenger Quick Start -- which has an [example of a Facebook message id.](https://developers.facebook.com/docs/messenger-platform/guides/quick-start#send_text_message)

**Comment by rapala61** [comment]
@aaronschachter 
I see this in the Slack RTM API docs about message events:

"The `channel` property is the ID of the channel, private group or DM channel this message is posted in. The `user` property is the ID of the user speaking, the `text` property is the text spoken, and `ts` is the unique (per-channel) timestamp."

Should this be the `platformMessageId`? It says is unique **per channel**.

**Comment by aaronschachter** [comment]
[Sounds right](https://api.slack.com/methods/channels.history#retrieving_a_single_message)!
