### ISSUE TITLE
Consolebot Photo command

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-conversations#72]
As a developer, I want to use a `photo` shortcut when using Consolebot to mock sending an image attachment to Gambit. This feature exists in the [Gambit Campaigns ConsoleBot.](https://github.com/DoSomething/gambit/blob/4.6.1/lib/consolebot.js#L34)

Refs https://github.com/DoSomething/gambit-conversations/pull/68#issuecomment-323128790

**Comment by rapala61** [comment]
Fixed in https://github.com/DoSomething/gambit-conversations/pull/82
