### ISSUE TITLE
Document Broadcasts

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-conversations#84]
We could use a new Wiki page to document the customer.io broadcast process, and link to it from our [Import Message documentation](https://github.com/DoSomething/gambit-conversations/blob/master/documentation/endpoints/import-message.md).

Refs [Send Message docs for Support.](https://github.com/DoSomething/gambit-conversations/blob/master/documentation/endpoints/send-message.md#support)

**Comment by rapala61** [comment]
![broadcasts v1 - page 1](https://user-images.githubusercontent.com/863301/29684850-713a65d2-88e1-11e7-80ee-5c7710c734cd.png)
